pipeline {
    agent any

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Select Terraform action'
        )
    }

    environment {
        TF_IN_AUTOMATION       = "true"
        TF_VAR_aws_access_key  = credentials('aws_access_key')    // Jenkins credentials
        TF_VAR_aws_secret_key  = credentials('aws_secret_key')    // Jenkins credentials
        AWS_DEFAULT_REGION     = "us-east-1"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'Githubaccess', url: 'https://github.com/KKDevOps07/GitOps.git', branch: 'master'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Fmt') {
            steps {
                dir('terraform') {
                    sh 'terraform fmt -recursive'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('terraform') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform') {
                    sh 'terraform plan -out=tfplan'
                }
            }
        }

        stage('Terraform Apply/Destroy') {
            steps {
                dir('terraform') {
                    sh "terraform ${params.ACTION} -auto-approve"
                }
            }
        }
    }

    post {
        always {
            echo "Terraform ${params.ACTION} pipeline complete"
        }
    }
}
